### ISSUE TITLE
Can't add plugin through Cordova CLI: Filename too long

### ISSUE THREAD

**Issue by blanedaze** [pbernasconi/cordova-progressIndicator#19]
I encountered this error when I tried to add it into a new Cordova project.

C:\testp>cordova plugin add https://github.com/pbernasconi/cordova-progressIndic
ator.git
Fetching plugin "https://github.com/pbernasconi/cordova-progressIndicator.git" v
ia git clone
Error: Command failed: Cloning into 'C:\Users\User\AppData\Local\Temp\git\143502
3689671'...
Checking out files:  23% (407/1729)
Checking out files:  24% (415/1729)
Checking out files:  24% (420/1729)
Checking out files:  25% (433/1729)
Checking out files:  26% (450/1729)
error: unable to create file demo/plugins/org.pbernasconi.progressIndicator/demo
/plugins/org.pbernasconi.progressIndicator/demo/platforms/ios/CordovaLib/Cordova
Lib.xcodeproj/xcuserdata/paolob.xcuserdatad/xcschemes/xcschememanagement.plist (
Filename too long)
error: unable to create file demo/plugins/org.pbernasconi.progressIndicator/demo
/plugins/org.pbernasconi.progressIndicator/demo/platforms/ios/CordovaLib/build/C
ordovaLib.build/Debug-iphonesimulator/CordovaLib.build/Cordova-all-target-header
s.hmap (Filename too long)
error: unable to create file demo/plugins/org.pbernasconi.progressIndicator/demo
/plugins/org.pbernasconi.progressIndicator/demo/platforms/ios/CordovaLib/build/C
ordovaLib.build/Debug-iphonesimulator/CordovaLib.build/Cordova-generated-files.h
map (Filename too long)
error: unable to create file demo/plugins/org.pbernasconi.progressIndicator/demo
/plugins/org.pbernasconi.progressIndicator/demo/platforms/ios/CordovaLib/build/C
ordovaLib.build/Debug-iphonesimulator/CordovaLib.build/Cordova-own-target-header
s.hmap (Filename too long)
error: unable to create file demo/plugins/org.pbernasconi.progressIndicator/demo
/plugins/org.pbernasconi.progressIndicator/demo/platforms/ios/CordovaLib/build/C
ordovaLib.build/Debug-iphonesimulator/CordovaLib.build/Cordova-project-headers.h
map (Filename too long)
fatal: cannot create directory at 'demo/plugins/org.pbernasconi.progressIndicato
r/demo/plugins/org.pbernasconi.progressIndicator/demo/platforms/ios/CordovaLib/b
uild/CordovaLib.build/Debug-iphonesimulator/CordovaLib.build/Objects-normal': Fi
lename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

 I had tried to use this plugin in Supersonic Appgyver app along with ngCordova, but it does not display any dialog, I'd then tried to use it on pure Cordova project, and I get the error above. Is there any way to fix it?

**Comment by yiqinglan** [comment]
met the same issue . even "git clone https://github.com/pbernasconi/cordova-progressIndicator.git" does not work.

**Comment by basdecort** [comment]
On Windows Git gets compiled with msys (old Windows API) which has a limit of 260 characters for a filename. You can change your GIT configuration to use longer filenames:

git config --system core.longpaths true

**Comment by githubramakrishnan** [comment]
HI @basdecort ,

Thank you, its working .
